# Generated by Django 6.0.5 on 2026-05-10 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('elapsed_seconds', models.FloatField(blank=True, null=True)),
                ('image_data', models.BinaryField(blank=True, null=True)),
                ('image_mime', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'search_queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=2000)),
                ('snippet', models.TextField(blank=True, null=True)),
                ('rank', models.IntegerField(default=1)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='search.searchquery')),
            ],
            options={
                'db_table': 'search_sources',
                'ordering': ['rank'],
            },
        ),
    ]
